# Generated by Django 5.2.5 on 2025-10-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_live_preview_url_review_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='live_preview_url',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Screenshot',
        ),
    ]
