# Generated by Django 5.2.5 on 2025-10-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_live_preview_url_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='live_preview_url',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
